services:
  - type: web
    name: esg-recommender
    env: python
    region: oregon
    plan: free
    buildCommand: "cd frontend && npm ci && npm run build && cd .. && mkdir -p api/static && cp -r frontend/build/* api/static/ && pip install -r requirements.txt"
    startCommand: "cd api && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 app:app"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
